---
name: latest-weekly

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Jenkins LTS version
        id: update
        uses: garethjevans/jenkins-version@0.1.2
        with:
          version-identifier: latest

      - name: Process Version
        id: process
        run: |
          SUFFIX=jdk11
          FULL_VERSION=jenkins/jenkins:${{ steps.update.outputs.jenkins_version }}-${SUFFIX}
          echo $FULL_VERSION
          sed -i 's|FROM .*|FROM '"${FULL_VERSION}"'|' Dockerfile

      - name: Calculate Diff
        id: diff
        run: |
          git diff

          if [[ $(git diff --stat) != '' ]]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      - name: Update
        if: ${{ steps.diff.outputs.changed == 'true' }}
        uses: garethjevans/uc@0.0.15
 
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'feat(deps): bump jenkins weekly to ${{ steps.update.outputs.jenkins_version }}'
          signoff: false
          title: 'feat(deps): bump jenkins weekly to ${{ steps.update.outputs.jenkins_version }}'
          branch: latest-weekly
